version: '3.4'
services:
  redis-overcommit:
    image: redis:5
    restart: 'no'
    privileged: true
    command: |
      bash -c "
        echo 1 > /mnt/vm/overcommit_memory ;
        echo never > /var/transparent_hugepage
      "
    volumes:
      - /proc/sys/vm:/mnt/vm
      - /sys/kernel/mm/transparent_hugepage:/mnt/transparent_hugepage

  redis:
    image: redis:5
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
      - ${USER_DATA_DIR}/docker/redis-data:/data
    depends_on:
      - redis-overcommit

  manticore:
    image: manticoresearch/manticore:3
    restart: unless-stopped
    volumes:
      - ./docker/sphinx.conf:/etc/sphinxsearch/sphinx.conf
      - ${USER_DATA_DIR}/docker/manticore-data:/var/lib/manticore/data

  mariadb:
    image: mariadb:10
    restart: unless-stopped
    volumes:
      - ./docker/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./docker/mariadb:/etc/mysql/conf.d
      - ${USER_DATA_DIR}/docker/mariadb-data:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: ${APP_TZ}

  nntmux: &nntmux
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    entrypoint: /entrypoint.sh
    container_name: nntmux
    hostname: nntmux
    domainname: arp.pw
    command: apachectl -D FOREGROUND
    volumes:
      - install-lock:/var/www/NNTmux/_install
    env_file: .env
    ports:
      - 8080:8080
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
      TZ: ${APP_TZ}
    depends_on:
      - mariadb
      - redis
      - manticore
  
  # nntmux-ui:
  #   <<: *nntmux
  #   container_name: nntmux-ui
  #   stdin_open: true
  #   tty: true
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
  #     TZ: ${APP_TZ}
  #     COLUMNS: "`tput cols`"
  #     LINES: "`tput lines`"
  #   command: php artisan tmux-ui:start
  #   ports:
  #     - 127.0.0.1:12345:12345

volumes:
  install-lock: